router_bgp:
  as: '65105'
  router_id: 1.1.1.6
  bgp_defaults:
  - distance bgp 20 200 200
  - no bgp default ipv4-unicast
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    MLAG-IPv4-UNDERLAY-PEER:
      type: ipv4
      remote_as: '65105'
      next_hop_self: true
      description: BL-01
      maximum_routes: 12000
      send_community: all
      route_map_in: RM-MLAG-PEER-IN
    UNDERLAY:
      type: ipv4
      maximum_routes: 12000
      send_community: all
      bgp_listen_range_prefix: 100.64.0.0/10
      peer_filter: Leaf-Ass
    OVERLAY:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '3'
      send_community: all
      maximum_routes: 0
  address_family_ipv4:
    peer_groups:
      MLAG-IPv4-UNDERLAY-PEER:
        activate: true
      UNDERLAY:
        activate: true
      OVERLAY:
        activate: false
  neighbors:
    10.255.251.8:
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: BL-01
    172.21.1.20:
      peer_group: UNDERLAY
      remote_as: '65000'
      description: Spine-01_Ethernet6
    172.21.1.22:
      peer_group: UNDERLAY
      remote_as: '65000'
      description: Spine-02_Ethernet6
    1.1.1.201:
      peer_group: OVERLAY
      description: Spine-01
      remote_as: '65000'
    1.1.1.202:
      peer_group: OVERLAY
      description: Spine-02
      remote_as: '65000'
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      OVERLAY:
        activate: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.22.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 8.8.8.8
spanning_tree:
  mode: none
  no_spanning_tree_vlan: 4093-4094
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$sbSVn6IgN2A7VIJJ$8g/z9ibMbFlO06jbpowU/PyB9kJvIgPNeSVyXjjanW8eftykpP7S32CFEdmb0nj0D8JXOKUNWe97T2wNvWSbm1
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$88e4YP9cN86RUUUZ$LBzKr2P.tfRkEZja4srfLK3t8TXCKx//t1LM59B6sr7AujC2HFTyKAsHZCxV/WOzHE/e7yrdlpMQxbaq/KW370
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 192.168.22.198/24
    gateway: 192.168.22.1
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
vlans:
  4093:
    tenant: system
    name: LEAF_PEER_L3
    trunk_groups:
    - LEAF_PEER_L3
  4094:
    tenant: system
    name: MLAG_PEER
    trunk_groups:
    - MLAG
vlan_interfaces:
  Vlan4093:
    description: MLAG_PEER_L3_PEERING
    shutdown: false
    ip_address: 10.255.251.9/31
    mtu: 1500
  Vlan4094:
    description: MLAG_PEER
    shutdown: false
    ip_address: 192.168.0.9/31
    no_autostate: true
    mtu: 1500
port_channel_interfaces:
  Port-Channel1000:
    description: MLAG_PEER_BL-01_Po1000
    type: switched
    shutdown: false
    vlans: 2-4094
    mode: trunk
    trunk_groups:
    - LEAF_PEER_L3
    - MLAG
ethernet_interfaces:
  Ethernet7:
    peer: BL-01
    peer_interface: Ethernet7
    peer_type: mlag_peer
    description: MLAG_PEER_BL-01_Ethernet7
    type: switched
    shutdown: false
    channel_group:
      id: 1000
      mode: active
  Ethernet8:
    peer: BL-01
    peer_interface: Ethernet8
    peer_type: mlag_peer
    description: MLAG_PEER_BL-01_Ethernet8
    type: switched
    shutdown: false
    channel_group:
      id: 1000
      mode: active
  Ethernet1:
    peer: Spine-01
    peer_interface: Ethernet6
    peer_type: spine
    description: Connection to Spine-01-Ethernet6
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.21.1.21/31
  Ethernet2:
    peer: Spine-02
    peer_interface: Ethernet6
    peer_type: spine
    description: Connection to Spine-02-Ethernet6
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.21.1.23/31
mlag_configuration:
  domain_id: DC1_BL
  local_interface: Vlan4094
  peer_address: 192.168.0.8
  peer_link: Port-Channel1000
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330
route_maps:
  RM-MLAG-PEER-IN:
    sequence_numbers:
      10:
        type: permit
        set:
        - origin incomplete
        description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
loopback_interfaces:
  Loopback0:
    description: RouterID_EVPN
    shutdown: false
    ip_address: 1.1.1.6/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 192.168.254.5/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 1.1.1.0/24 eq 32
      20:
        action: permit 192.168.254.0/24 eq 32
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
vxlan_interface:
  Vxlan1:
    description: BL-02_VTEP
    vxlan:
      source_interface: Loopback1
      virtual_router_encapsulation_mac_address: mlag-system-id
      udp_port: 4789
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.fr.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.fr.pool.ntp.org
    preferred: false
    vrf: MGMT
