router_bgp:
  as: '65004'
  router_id: 1.1.1.4
  bgp_defaults:
  - no bgp default ipv4-unicast
  - maximum-paths 8 ecmp 8
  peer_groups:
    UNDERLAY:
      type: ipv4
      maximum_routes: 12000
      send_community: all
      bgp_listen_range_prefix: 100.64.0.0/10
      peer_filter: Leaf-Ass
      remote_as: '65000'
    EVPN:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '3'
      send_community: all
      maximum_routes: 0
      bgp_listen_range_prefix: 1.1.1.0/24
      peer_filter: Leaf-Ass
      remote_as: '65000'
  address_family_ipv4:
    peer_groups:
      UNDERLAY:
        activate: true
      EVPN:
        activate: false
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  neighbors:
    100.100.0.12:
      peer_group: UNDERLAY
      type: ipv4
      remote_as: '65000'
      description: Spine-01
    100.100.0.14:
      peer_group: UNDERLAY
      type: ipv4
      remote_as: '65000'
      description: Spine-02
    1.1.1.201:
      peer_group: EVPN
      description: Spine-01
      remote_as: '65000'
    1.1.1.202:
      peer_group: EVPN
      description: Spine-02
      remote_as: '65000'
  address_family_evpn:
    peer_groups:
      EVPN:
        activate: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.22.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 8.8.8.8
spanning_tree:
  mode: none
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$sbSVn6IgN2A7VIJJ$8g/z9ibMbFlO06jbpowU/PyB9kJvIgPNeSVyXjjanW8eftykpP7S32CFEdmb0nj0D8JXOKUNWe97T2wNvWSbm1
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$88e4YP9cN86RUUUZ$LBzKr2P.tfRkEZja4srfLK3t8TXCKx//t1LM59B6sr7AujC2HFTyKAsHZCxV/WOzHE/e7yrdlpMQxbaq/KW370
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 192.168.22.196/24
    gateway: 192.168.22.1
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
p2p_ipv4_pool: 100.100.0.0/30
switch_id: 4
ethernet_interfaces:
  Ethernet1:
    peer: Spine-01
    peer_interface: Ethernet4
    peer_type: spine
    description: Connection to Spine-01-Ethernet4
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 100.100.0.13/31
  Ethernet2:
    peer: Spine-02
    peer_interface: Ethernet4
    peer_type: spine
    description: Connection to Spine-02-Ethernet4
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 100.100.0.15/31
  Ethernet3:
    peer: Shared
    peer_interface: Eth1
    peer_type: server
    description: Shared_Eth1
    type: switched
    shutdown: false
    mode: trunk
loopback_interfaces:
  Loopback0:
    description: RouterID_EVPN
    shutdown: false
    ip_address: 1.1.1.4/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 2.2.2.4/32
prefix_lists:
- name: Loopback
  sequence_numbers:
  - sequence: 10
    action: permit 1.1.1.0/24 eq 32
- name: Loopback
  sequence_numbers:
  - sequence: 20
    action: permit 2.2.2.0/24 eq 32
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
vxlan_interface:
  Vxlan1:
    description: VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.fr.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.fr.pool.ntp.org
    preferred: false
    vrf: MGMT
