# Management API HTTP
management_api_http:
  enable_http: true
  enable_https: false
  https_ssl_profile: SSL_PROFILE
  enable_vrfs:
    - name: default
      access_group: ACL-API
    - name: MGMT
      access_group: ACL-API

# Standard ACLs
standard_access_lists:
  - name: ACL-API
    sequence_numbers:
      - sequence: 10
        action: "permit 10.0.0.0/8"
      - sequence: 20
        action: "permit 100.0.0.0/8"
