class GenernalConfiguration():
  """
  genernal configuration domain 2022.06.27 pks
  """
  def __init__(self):
    self.sheetName = "General Configuration Details"
    self.fabricName = "Fabric Name"
    self.configletPrefix = "Configlet Prefix"
    self.fabricIdentifier = "Fabric Identifier"
    self.validateNetworkWithBatfish = "Validate Network with Batfish"
    self.managementInterface = "Management Interface"
    self.managementInterfaceVrf = "Management Interface VRF"
    self.managementGateway = "Management Gateway"
    self.dnsServers = "DNS Servers"
    self.ntpServers = "NTP Servers"
    self.ntpServersPrefer = "NTP Servers Prefer"
    self.underlayNetworkSummary = "Underlay Network Summary"
    self.overlayNetworkSummary = "Overlay Network Summary"
    self.vtepNetworkSummary = "VTEP Network Summary"
    self.vxlanVlanAwareBundles = "Vxlan VLAN Aware Bundles"
    self.mlagIgpPeerNetworkSummary = "MLAG IGP Peer Network Summary"
    self.mlagPeerNetworkSummary = "MLAG Peer Network Summary"
    self.bgpIpv4UnderlayPeerGroupPassword = "BGP IPv4 Underlay Peer Group Password"
    self.bgpEvpnOverlayPeerGroupPassword = "BGP EVPN Overlay Peer Group Password"
    self.bgpMlagIpv4UnderlayGroupPassword = "BGP MLAG IPv4 Underlay Group Password"
    self.pointToPointUplinkMtu = "Point to Point Uplink MTU"
    self.bgpBfdMultihopInterval = "BGP BFD Multihop Interval"
    self.bgpBfdMultihopMinRx = "BGP BFD Multihop Min Rx"
    self.bgpBfdMultihopMultiplier = "BGP BFD Multihop Multiplier"
    self.adminPassword = "admin paasword sha512 hash"
    self.ansiblePassword = "ansible password sha512 hash"
    self.cvpIpAddress = "CVP IP Addresses"
    self.cvpIngestAuthKey = "CVP Ingest Auth Key"