# Minimum config to only test the specific feature.
l2leaf:
  defaults:
  nodes:
    mgmt_interface_default:
      mgmt_interface_vrf: MGMT
      mgmt_gateway: 1.1.1.1
      mgmt_ip: 1.1.1.2
      id: 102
