### Route-maps ###
route_maps:
  - name: RM-CONN-BL-BGP
    sequence_numbers:
      - sequence: 10
        type: deny
        match:
          - ip address prefix-list PL-MLAG
      - sequence: 20
        type: permit
  - name: RM-STATIC-2-BGP
    sequence_numbers:
      - sequence: 10
        description: tag for static routes
        type: permit
        set:
          - tag 65100
  - name: RM-HIDE-ASPATH-IN
    sequence_numbers:
      - sequence: 10
        type: permit
        set:
          - as-path match all replacement auto
          - community 65000:1 additive
  - name: RM-HIDE-ASPATH-OUT
    sequence_numbers:
      - sequence: 10
        type: deny
        match:
          - community LIST-COM
      - sequence: 20
        type: permit
        set:
          - as-path match all replacement auto
  - name: RM-MLAG-PEER-IN
    sequence_numbers:
      - sequence: 10
        type: permit
        set:
          - "origin incomplete"
  - name: RM-10.2.3.4-SET-NEXT-HOP-OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        set:
          - ip next-hop 10.2.3.4
